<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.324">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Brandon Scott">
<meta name="dcterms.date" content="2022-12-24">

<title>The Bayesian Bandit - Simple Linear Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">The Bayesian Bandit</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://thebayesianbandit.com/book" rel="" target="">
 <span class="menu-text">Book</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/thebayesianbandit" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/brandon-scott-5a7139211/" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Simple Linear Regression</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">analysis</div>
                <div class="quarto-category">bayesian</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Brandon Scott </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">December 24, 2022</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">0.1</span> Introduction</a></li>
  <li><a href="#exploratory-data-analysis-eda" id="toc-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda"><span class="header-section-number">0.2</span> Exploratory Data Analysis (EDA)</a>
  <ul class="collapse">
  <li><a href="#import-data-and-libraries" id="toc-import-data-and-libraries" class="nav-link" data-scroll-target="#import-data-and-libraries"><span class="header-section-number">0.2.1</span> Import data and libraries</a></li>
  <li><a href="#data-cleaning" id="toc-data-cleaning" class="nav-link" data-scroll-target="#data-cleaning"><span class="header-section-number">0.2.2</span> Data Cleaning</a></li>
  </ul></li>
  <li><a href="#data-viz" id="toc-data-viz" class="nav-link" data-scroll-target="#data-viz"><span class="header-section-number">0.3</span> Data Viz</a></li>
  <li><a href="#classical-modeling" id="toc-classical-modeling" class="nav-link" data-scroll-target="#classical-modeling"><span class="header-section-number">0.4</span> Classical Modeling</a>
  <ul class="collapse">
  <li><a href="#linear-regression-framework" id="toc-linear-regression-framework" class="nav-link" data-scroll-target="#linear-regression-framework"><span class="header-section-number">0.4.1</span> Linear Regression Framework</a></li>
  <li><a href="#calculate-beta-values-and-interpret-results" id="toc-calculate-beta-values-and-interpret-results" class="nav-link" data-scroll-target="#calculate-beta-values-and-interpret-results"><span class="header-section-number">0.4.2</span> Calculate beta values and interpret results</a></li>
  <li><a href="#is-study-hours-a-statistically-significant-variable-in-determining-gpa" id="toc-is-study-hours-a-statistically-significant-variable-in-determining-gpa" class="nav-link" data-scroll-target="#is-study-hours-a-statistically-significant-variable-in-determining-gpa"><span class="header-section-number">0.4.3</span> Is study hours a statistically significant variable in determining GPA?</a></li>
  <li><a href="#check-assumptions-of-linear-regression-model" id="toc-check-assumptions-of-linear-regression-model" class="nav-link" data-scroll-target="#check-assumptions-of-linear-regression-model"><span class="header-section-number">0.4.4</span> Check assumptions of linear regression model</a></li>
  <li><a href="#do-students-spend-on-average-9-hours-a-week-studying" id="toc-do-students-spend-on-average-9-hours-a-week-studying" class="nav-link" data-scroll-target="#do-students-spend-on-average-9-hours-a-week-studying"><span class="header-section-number">0.4.5</span> Do students spend on average 9 hours a week studying?</a></li>
  </ul></li>
  <li><a href="#bayesian-modeling" id="toc-bayesian-modeling" class="nav-link" data-scroll-target="#bayesian-modeling"><span class="header-section-number">0.5</span> Bayesian Modeling</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="introduction" class="level2" data-number="0.1">
<h2 data-number="0.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">0.1</span> Introduction</h2>
The hope of this analysis is to demonstrate that there is a quantifiable relationship between GPA and study hours. We recognize that the collected data was self reported and therefore can be dishonest. Nonetheless, our goal is to still find a way to quantify a relationship between GPA and study hours to:
<ol>
<li>
Gather inference to determine how GPA changes based on increase study time
</li>
<li>
Predict what a student’s GPA would be based on study time
</li>
</ol>
<p>Data for this analysis can be found <a href="https://www.kaggle.com/datasets/joebeachcapital/gpa-study-hours">here</a></p>
</section>
<section id="exploratory-data-analysis-eda" class="level2" data-number="0.2">
<h2 data-number="0.2" class="anchored" data-anchor-id="exploratory-data-analysis-eda"><span class="header-section-number">0.2</span> Exploratory Data Analysis (EDA)</h2>
<section id="import-data-and-libraries" class="level3" data-number="0.2.1">
<h3 data-number="0.2.1" class="anchored" data-anchor-id="import-data-and-libraries"><span class="header-section-number">0.2.1</span> Import data and libraries</h3>
<p>We begin our analysis by importing the following libraries to create data visualizations as well as properly format and filter our data.</p>
<div class="cell" data-tags="[]" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Import libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> opendatasets <span class="im">as</span> od</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We read in our data using pandas and will use the head function to check out the data.</p>
<div class="cell" data-tags="[]" data-execution_count="4">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check dataframe</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">gpa</th>
<th data-quarto-table-cell-role="th">study_hours</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>4.00</td>
<td>10.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>3.80</td>
<td>25.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>3.93</td>
<td>45.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>3.40</td>
<td>10.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>3.20</td>
<td>4.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The head result indicates that the data has been read in correctly. In the next section, we will begin to clean the data.</p>
</section>
<section id="data-cleaning" class="level3" data-number="0.2.2">
<h3 data-number="0.2.2" class="anchored" data-anchor-id="data-cleaning"><span class="header-section-number">0.2.2</span> Data Cleaning</h3>
<p>We will begin our data cleaning by getting some basic summary statistics from the dataframe.</p>
<div class="cell" data-tags="[]" data-execution_count="5">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Describe dataset</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>df.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">gpa</th>
<th data-quarto-table-cell-role="th">study_hours</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>193.000000</td>
<td>193.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>3.586166</td>
<td>17.476684</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>0.285482</td>
<td>11.408980</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>2.600000</td>
<td>2.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>3.400000</td>
<td>10.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>3.620000</td>
<td>15.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>3.800000</td>
<td>20.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>4.300000</td>
<td>69.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The resulting dataframe shows that we have 193 rows of data where on average the gpa is 3.58 with a standard deviation of .28. Average study hours show 17.47 and standard deviation of 11.4, meaning we have a large spread in the distribution of study hours but not too much in gpa. From the summary statistics, we can easily see that the max value is invalid as the scale we are using for this analysis is 0-4. We will eliminate any rows that fall outside of this range.</p>
<div class="cell" data-tags="[]" data-execution_count="6">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check datatypes</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>df.dtypes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>gpa            float64
study_hours    float64
dtype: object</code></pre>
</div>
</div>
<p>Checking the datatypes of each of the columns, we see that each is of type float. This confirms that all rows in each column are of the same datatype and, in theory, we do not need to clean up any corrupted data/poorly entered data.</p>
<div class="cell" data-tags="[]" data-execution_count="7">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check for null values</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>df.isnull().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>gpa            0
study_hours    0
dtype: int64</code></pre>
</div>
</div>
<p>In addition, checking for nulls, we see there are none so we do not need to do anything with those. In the next code chunk, we will eliminate erroneous gpa entries.</p>
<div class="cell" data-tags="[]" data-execution_count="8">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Convert outlier GPA (erroneous entries) to 4.0</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.assign(gpa <span class="op">=</span> <span class="kw">lambda</span> x: np.where(x.gpa <span class="op">&gt;</span> <span class="dv">4</span>, <span class="dv">4</span>, x.gpa))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the above chunk, we use the assign function to override the gpa column and change values that are above 4 to just 4 while leaving all others the same.</p>
</section>
</section>
<section id="data-viz" class="level2" data-number="0.3">
<h2 data-number="0.3" class="anchored" data-anchor-id="data-viz"><span class="header-section-number">0.3</span> Data Viz</h2>
<p>The first visualization we will look at is comparing the distributions of gpa and study hours. We want to get a side by side look so we will use the subplots functionality from matplotlib. As well, we will plot the median of the two respective distributions to know where the 50% percentile lies. The following code produces <a href="#fig-dist-1">Figure&nbsp;1</a>.</p>
<div class="cell" data-tags="[]" data-execution_count="9">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check distributios of gpa and study hours</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize <span class="op">=</span> (<span class="dv">18</span>, <span class="dv">5</span>))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>sns.histplot(x<span class="op">=</span><span class="st">"gpa"</span>, data<span class="op">=</span>df, ax<span class="op">=</span>ax1, bins<span class="op">=</span><span class="dv">15</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>ax1.axvline(df.gpa.median(), color<span class="op">=</span><span class="st">"black"</span>, linestyle<span class="op">=</span><span class="st">"dashed"</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>ax1.text(df.gpa.median() <span class="op">-</span> <span class="fl">0.3</span>, ax1.get_ylim()[<span class="dv">1</span>] <span class="op">*</span> <span class="fl">0.9</span>, <span class="ss">f"Median: </span><span class="sc">{</span>df<span class="sc">.</span>gpa<span class="sc">.</span>median()<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>sns.histplot(x<span class="op">=</span><span class="st">"study_hours"</span>, data<span class="op">=</span>df, ax<span class="op">=</span>ax2, color<span class="op">=</span><span class="st">"red"</span>, bins<span class="op">=</span><span class="dv">15</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>ax2.axvline(df.study_hours.median(), color<span class="op">=</span><span class="st">"black"</span>, linestyle<span class="op">=</span><span class="st">"dashed"</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>ax2.text(df.study_hours.median() <span class="op">+</span> <span class="dv">2</span>, ax2.get_ylim()[<span class="dv">1</span>] <span class="op">*</span> <span class="fl">0.9</span>, <span class="ss">f"Median: </span><span class="sc">{</span>df<span class="sc">.</span>study_hours<span class="sc">.</span>median()<span class="sc">:.2f}</span><span class="ss">"</span>)<span class="op">;</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="co">#fig.suptitle("Distributions of GPA and Study Hours");</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-dist-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="gpa_analysis_files/figure-html/fig-dist-1-output-1.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;1: Distributions of GPA and Study Hours</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>From <a href="#fig-dist-1">Figure&nbsp;1</a>, we see that GPA appears to be slightly left skewed with a couple of outliers to the left of the distribution. Study hours appears to be more right skewed with more outliers towards the right of the distribution. Median for GPA is 3.62 and 15 for study hours.</p>
<p>Since we are working with two quantitative variables, we can use a scatterplot to view how linear their relationship (ie correlation) as well as view the where each gpa falls for a given amount of study hour. The below code produces <a href="#fig-scatterplot-1">Figure&nbsp;2</a>.</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Scatterplot of gpa and study hours</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">15</span>,<span class="dv">5</span>))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>sns.regplot(x<span class="op">=</span><span class="st">'study_hours'</span>, y<span class="op">=</span><span class="st">'gpa'</span>, data<span class="op">=</span>df)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>corr_coef <span class="op">=</span> np.corrcoef(df.study_hours, df.gpa)[<span class="dv">0</span>][<span class="dv">1</span>]</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>plt.text(<span class="dv">50</span>, <span class="fl">2.8</span>, <span class="ss">f"Correlation: </span><span class="sc">{</span>corr_coef<span class="sc">:.2f}</span><span class="ss">"</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-scatterplot-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="gpa_analysis_files/figure-html/fig-scatterplot-1-output-1.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;2: Scatterplot of GPA by Study Hours</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><a href="#fig-scatterplot-1">Figure&nbsp;2</a> shows that the linear relationship between study hours and GPA is not very strong. An exact score of .14 for the correlation indicates a weak linear relationship. Further more, like we already saw from the histograms, the data appears to be more grouped towards the beginning of the x axis (0-20ish hours).</p>
<p>We can attempt to adjust the distribution and correlation of the dataset by removing outliers. However, because the outlying dots appear to follow the trend of the data (more or less…) and we always like keeping as much data as possible, this is merely an optional step to fulfill our curiosity.</p>
<p>We will define an outlier as a point that falls outside of a box-plot range. Below is the function we will use to define and identify outliers.</p>
<div class="cell" data-tags="[]" data-execution_count="11">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Identify outliers</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> find_outliers(x, column_name):</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    q1 <span class="op">=</span> x[column_name].quantile(<span class="fl">.25</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    q3 <span class="op">=</span> x[column_name].quantile(<span class="fl">.75</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    iqr <span class="op">=</span> q3 <span class="op">-</span> q1</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    lower <span class="op">=</span> q1 <span class="op">-</span> (<span class="fl">1.5</span> <span class="op">*</span> iqr)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    upper <span class="op">=</span> q3 <span class="op">+</span> (<span class="fl">1.5</span> <span class="op">*</span> iqr)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    outliers <span class="op">=</span> x[(x[column_name] <span class="op">&lt;</span> lower) <span class="op">|</span> (x[column_name] <span class="op">&gt;</span> upper)]</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> outliers</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The function calculates the IQR of the dataset and then returns a filtered dataframe based on whether a point passes the upper or lower bound of the box-plot. For example, below we see how the function identifies outliers using the GPA attribute.</p>
<div class="cell" data-tags="[]" data-execution_count="12">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Find outliers for gpa</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>find_outliers(df, <span class="st">"gpa"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">gpa</th>
<th data-quarto-table-cell-role="th">study_hours</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">108</td>
<td>2.6</td>
<td>7.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Similarily, we can view the outliers for study hours below.</p>
<div class="cell" data-scrolled="true" data-tags="[]" data-execution_count="13">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Find outliers for study hours</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>find_outliers(df, <span class="st">"study_hours"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">gpa</th>
<th data-quarto-table-cell-role="th">study_hours</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>3.930</td>
<td>45.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>3.400</td>
<td>40.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">13</td>
<td>3.830</td>
<td>60.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">51</td>
<td>3.868</td>
<td>40.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">57</td>
<td>3.125</td>
<td>36.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">77</td>
<td>3.566</td>
<td>40.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">83</td>
<td>3.850</td>
<td>69.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">89</td>
<td>3.700</td>
<td>45.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">122</td>
<td>3.750</td>
<td>40.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">125</td>
<td>3.500</td>
<td>49.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">130</td>
<td>3.825</td>
<td>60.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">135</td>
<td>3.600</td>
<td>40.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">169</td>
<td>3.830</td>
<td>60.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><a href="#fig-scatter-outliers">Figure&nbsp;3</a> below shows which points are labeled as outliers from our scatterplot.</p>
<div class="cell" data-tags="[]" data-execution_count="14">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot original scatterplot</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">15</span>,<span class="dv">5</span>))</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>sns.regplot(x<span class="op">=</span><span class="st">'study_hours'</span>, y<span class="op">=</span><span class="st">'gpa'</span>, data<span class="op">=</span>df)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>corr_coef <span class="op">=</span> np.corrcoef(df.study_hours, df.gpa)[<span class="dv">0</span>][<span class="dv">1</span>]</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>plt.text(<span class="dv">50</span>, <span class="fl">2.8</span>, <span class="ss">f"Correlation: </span><span class="sc">{</span>corr_coef<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Show outliers by study hours (color red)</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x<span class="op">=</span><span class="st">'study_hours'</span>, y<span class="op">=</span><span class="st">'gpa'</span>, data<span class="op">=</span>find_outliers(df, <span class="st">"study_hours"</span>), color<span class="op">=</span><span class="st">'red'</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Show outliers by gpa (color yellow)</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x<span class="op">=</span><span class="st">'study_hours'</span>, y<span class="op">=</span><span class="st">'gpa'</span>, data<span class="op">=</span>find_outliers(df, <span class="st">"gpa"</span>), color<span class="op">=</span><span class="st">'yellow'</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-scatter-outliers" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="gpa_analysis_files/figure-html/fig-scatter-outliers-output-1.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3: Scatterplot of GPA and Study Hours (highlighted outliers)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>As already indicated, the red dots are outliers according to the “study hours” metric while yellow indicates outlier for “gpa”. While the red dots are technically “outliers”, they do sort of follow the general trend and direction of the data whereas the yellow dot does not. Let’s try removing the yellow dot to see how it changes the correlation of the data.</p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Remove outliers from dataset</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>df_filtered <span class="op">=</span> df.query(<span class="st">"gpa &gt; 2.6"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After removing the gpa outlier, the scatterplot and corresponding correlation are as follows.</p>
<div class="cell" data-tags="[]" data-execution_count="16">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Scatterplot of gpa and study hours</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">15</span>,<span class="dv">5</span>))</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>sns.regplot(x<span class="op">=</span><span class="st">'study_hours'</span>, y<span class="op">=</span><span class="st">'gpa'</span>, data<span class="op">=</span>df_filtered)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>corr_coef <span class="op">=</span> np.corrcoef(df_filtered.study_hours, df_filtered.gpa)[<span class="dv">0</span>][<span class="dv">1</span>]</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>plt.text(<span class="dv">50</span>, <span class="fl">2.8</span>, <span class="ss">f"Correlation: </span><span class="sc">{</span>corr_coef<span class="sc">:.2f}</span><span class="ss">"</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-scatterplot-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="gpa_analysis_files/figure-html/fig-scatterplot-2-output-1.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;4: Scatterplot of GPA by Study Hours (filtered)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>We see that removing the gpa outlier had a minimal effect on the correlation (actually slightly decreased) thus “weakening” the linear relationship of the variables. Perhaps we can try a non-linear transformation to aid our non-linear data.</p>
<p>To do this, we will perform a log transformation on both gpa and study hours (on our original dataset) and a polynomial transformation on study hours. Below is the result of our transformations.</p>
<div class="cell" data-tags="[]" data-execution_count="17">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot log transformed data</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize <span class="op">=</span> (<span class="dv">18</span>, <span class="dv">5</span>))</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>sns.regplot(x<span class="op">=</span><span class="st">'study_hours'</span>, y<span class="op">=</span><span class="st">'gpa'</span>, data<span class="op">=</span>np.log(df), ax<span class="op">=</span>ax1)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>ax1.set_xlabel(<span class="st">"log(study_hours)"</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>ax1.set_ylabel(<span class="st">"log(gpa)"</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>corr_coef <span class="op">=</span> np.corrcoef(df.study_hours, df.gpa)[<span class="dv">0</span>][<span class="dv">1</span>]</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>ax1.text(np.log(<span class="dv">30</span>), np.log(<span class="fl">2.8</span>), <span class="ss">f"Correlation: </span><span class="sc">{</span>corr_coef<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot polynomial transformed data</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>df_poly <span class="op">=</span> df.assign(study_hours <span class="op">=</span> <span class="kw">lambda</span> x: x.study_hours<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>sns.regplot(x<span class="op">=</span><span class="st">'study_hours'</span>, y<span class="op">=</span><span class="st">'gpa'</span>, data<span class="op">=</span>df_poly, ax<span class="op">=</span>ax2)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>ax2.set_xlabel(<span class="st">"study_hours^2"</span>)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>corr_coef <span class="op">=</span> np.corrcoef(df.study_hours, df.gpa)[<span class="dv">0</span>][<span class="dv">1</span>]</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>ax2.text(<span class="dv">50</span><span class="op">**</span><span class="dv">2</span>, <span class="fl">2.8</span>, <span class="ss">f"Correlation: </span><span class="sc">{</span>corr_coef<span class="sc">:.2f}</span><span class="ss">"</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-transformations" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="gpa_analysis_files/figure-html/fig-transformations-output-1.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;5: Scatterplot of GPA by Study Hours (filtered)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-transformations">Figure&nbsp;5</a>, we see that our transformations really had not effect on the linear relationship. For the sake of getting on with the modeling, we will use our base dataset and interpret the model accordingly (barring that the other model assumptions hold).</p>
</section>
<section id="classical-modeling" class="level2" data-number="0.4">
<h2 data-number="0.4" class="anchored" data-anchor-id="classical-modeling"><span class="header-section-number">0.4</span> Classical Modeling</h2>
<p>This section will be our first attempt at modeling the data, using classical (frequentist) style approaches. Even though this is thebayesianbandit, I like providing frequentist approaches as well to show the differences and similarities between normal statistical modeling (frequentist) and bayesian modeling.</p>
<section id="linear-regression-framework" class="level3" data-number="0.4.1">
<h3 data-number="0.4.1" class="anchored" data-anchor-id="linear-regression-framework"><span class="header-section-number">0.4.1</span> Linear Regression Framework</h3>
<p>Since we are dealing with “linear” data, it would make sense to attempt to attempt to fit a linear model to the data. Therefore, we will be utilizing a simple linear regression (SLR) model to model the relationship between GPA and study hours (per week). Below is the equation we will use.</p>
<p><span id="eq-linear-model"><span class="math display">\[
y = X\beta + \epsilon
\tag{1}\]</span></span> <span class="math display">\[\epsilon \sim N(\mu, \sigma^2)\]</span></p>
<p><a href="#eq-linear-model">Equation&nbsp;1</a> models our response variable is equal to our matrix of explanatory variables (in this case, just one) multiplied (scaled) by a matrix of betas, plus errors (residuals) that are distributed normally with mean <span class="math inline">\(\mu\)</span> and variance <span class="math inline">\(\sigma^2\)</span></p>
<p>In linear algebra/matrix notation, it would look something like this.</p>
<p><span id="eq-linear-model-matrix"><span class="math display">\[
\begin{bmatrix}
y_1 \\
... \\
y_n
\end{bmatrix}
=
\begin{bmatrix}
1 &amp; x_1 \\
... &amp; ... \\
1 &amp; x_n \\
\end{bmatrix}
\begin{bmatrix}
\beta_0 \\
\beta_1
\end{bmatrix}
+
\begin{bmatrix}
\epsilon_1 \\
... \\
\epsilon_n
\end{bmatrix}
\tag{2}\]</span></span></p>
<p>We utilize ordinary least squares (OLS) to estimate our coefficients (<span class="math inline">\(\beta\)</span> values) by minimizing the residual sum of squares (RSS). Below are the equations we will use.</p>
<p><span id="eq-residual-sum-squares"><span class="math display">\[
RSS = \epsilon^2_1 + ... + \epsilon^2_n
\tag{3}\]</span></span></p>
<p><span id="eq-residuals"><span class="math display">\[
\epsilon = y_i - \hat{y_i}
\tag{4}\]</span></span></p>
<p><span id="eq-beta-1"><span class="math display">\[
\hat{\beta_1} = \frac{\sum_{i=1}^{n}(x_i - \bar{x})(y_i - \bar{y})}{\sum_{i=1}^{n}(x_i - \bar{x})^2}
\tag{5}\]</span></span></p>
<p><span id="eq-beta-0"><span class="math display">\[
\hat{\beta_0} = \bar{y} - \hat{\beta_1}\bar{x}
\tag{6}\]</span></span></p>
<p>By estimating our coefficients like this, we have a mathematical framework of estimating the line of best fit (the average line between all data points). This yields are final equation below.</p>
<p><span id="eq-linear-hat"><span class="math display">\[
\hat{y} = X\hat{\beta}
\tag{7}\]</span></span></p>
<p>Where <span class="math inline">\(\hat{y}\)</span> is our “predicted” value based off our inputs in the matrix of <span class="math inline">\(X\)</span>, scaled/multiplied by <span class="math inline">\(\hat{\beta}\)</span>, our estimated coefficients.</p>
</section>
<section id="calculate-beta-values-and-interpret-results" class="level3" data-number="0.4.2">
<h3 data-number="0.4.2" class="anchored" data-anchor-id="calculate-beta-values-and-interpret-results"><span class="header-section-number">0.4.2</span> Calculate beta values and interpret results</h3>
<p>Now that we have our framework by which we will fit our data, we can use Python libraries to perform the above calculations.</p>
<div class="cell" data-tags="[]" data-execution_count="29">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Import statsmod and fit SLR model</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">'gpa'</span>]</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> pd.DataFrame({<span class="st">'intercept'</span>:np.ones(df.shape[<span class="dv">0</span>]), <span class="st">'study_hours'</span>:df[<span class="st">'study_hours'</span>]})</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> sm.OLS(y, X)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> model.fit()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-scrolled="true" data-tags="[]" data-execution_count="33">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Print summary from SLR model</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>results.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="33">
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>OLS Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>gpa</td>
<td data-quarto-table-cell-role="th">R-squared:</td>
<td>0.019</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>OLS</td>
<td data-quarto-table-cell-role="th">Adj. R-squared:</td>
<td>0.014</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>Least Squares</td>
<td data-quarto-table-cell-role="th">F-statistic:</td>
<td>3.714</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Wed, 06 Sep 2023</td>
<td data-quarto-table-cell-role="th">Prob (F-statistic):</td>
<td>0.0555</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>20:33:28</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>-27.443</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>193</td>
<td data-quarto-table-cell-role="th">AIC:</td>
<td>58.89</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>191</td>
<td data-quarto-table-cell-role="th">BIC:</td>
<td>65.41</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>1</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">t</td>
<td data-quarto-table-cell-role="th">P&gt;|t|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">intercept</td>
<td>3.5249</td>
<td>0.037</td>
<td>95.292</td>
<td>0.000</td>
<td>3.452</td>
<td>3.598</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">study_hours</td>
<td>0.0034</td>
<td>0.002</td>
<td>1.927</td>
<td>0.055</td>
<td>-8.05e-05</td>
<td>0.007</td>
</tr>
</tbody>
</table>
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Omnibus:</td>
<td>10.671</td>
<td data-quarto-table-cell-role="th">Durbin-Watson:</td>
<td>2.385</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Prob(Omnibus):</td>
<td>0.005</td>
<td data-quarto-table-cell-role="th">Jarque-Bera (JB):</td>
<td>11.481</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Skew:</td>
<td>-0.595</td>
<td data-quarto-table-cell-role="th">Prob(JB):</td>
<td>0.00321</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Kurtosis:</td>
<td>2.897</td>
<td data-quarto-table-cell-role="th">Cond. No.</td>
<td>38.3</td>
</tr>
</tbody>
</table>
<br><br>Notes:<br>[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
</div>
</div>
<p>From the summary, we have <span class="math inline">\(\beta_0\)</span> = 3.5249 and <span class="math inline">\(\beta_1\)</span> = .0034, meaning on average someone who studies 0 hours a week would see a GPA value of about 3.5. In addition, on average, for an increase of 1 hour in study time, we would see an increase of about .0034 in GPA. This isn’t too surprising considering the weak linear relationship we observed earlier in <a href="#fig-scatterplot-1">Figure&nbsp;2</a>. Essentially, if I were a student in this class, in order to change a whole letter grade (i.e.&nbsp;go from B to B+) and assuming I was right at B level (3.0), I would need to study 88 extra hours. Essentially, this model says that you’re stuck where you’re at.</p>
Nevertheless, we can gain confidence in knowing a couple of things.
<ol>
<li>
The data has a fairly weak linear relationship, so using a linear model to fit the data may not tell the most accurate story on how GPA is influenced by study hours.
</li>
<li>
The data could be inaccurate due to self-reporting
</li>
</ol>
</section>
<section id="is-study-hours-a-statistically-significant-variable-in-determining-gpa" class="level3" data-number="0.4.3">
<h3 data-number="0.4.3" class="anchored" data-anchor-id="is-study-hours-a-statistically-significant-variable-in-determining-gpa"><span class="header-section-number">0.4.3</span> Is study hours a statistically significant variable in determining GPA?</h3>
<p>To determine the answer to the above question, we pose the following hypotheses.</p>
<p><span class="math display">\[
H_0: \beta_1 = 0
\]</span> <span class="math display">\[
H_a: \beta_1 \neq 0
\]</span></p>
<p>The aim of these hypotheses is to determine whether or not <span class="math inline">\(\beta_1\)</span> on average always has some kind of impact on GPA (whether it is an increase or decrease, no one knows in these things). We set our <span class="math inline">\(\alpha\)</span> = .05 to run our hypotheses.</p>
<p>The p-value we obtain from the summary print out indicates that p-value &gt; <span class="math inline">\(\alpha\)</span>, so we fail to reject <span class="math inline">\(H_0\)</span> and conclude that there isn’t sufficient evidence to reject the null. Essentially, we don’t have enough statistical evidence from the data to prove that study hours, on average, will never have a 0 impact on GPA.</p>
<p>To confirm this notion, we can view the corresponding 95% confidence interval for <span class="math inline">\(\beta_1\)</span> provided in the summary tab. The values of (-.000085, .007) indicate that 0 is included in the interval and therefore, the average change on GPA based on study hours can be 0.</p>
</section>
<section id="check-assumptions-of-linear-regression-model" class="level3" data-number="0.4.4">
<h3 data-number="0.4.4" class="anchored" data-anchor-id="check-assumptions-of-linear-regression-model"><span class="header-section-number">0.4.4</span> Check assumptions of linear regression model</h3>
Even though the <span class="math inline">\(\beta_1\)</span> value proved to not be statistically significant (though very close), we should still verify that the assumptions of our linear model hold with this data set. The assumptions for a linear regression model are listed below.
<ol>
<li>
Linearity
</li>
<li>
Independence
</li>
<li>
Normality
</li>
<li>
Equal Variance
</li>
</ol>
<p>We already verified that there is a weak linear relationship, but still a linear relationship since correlation was not 0. Independence is verified by the fact that each observation in the study was independent of one another, thus making them i.i.d random variables.</p>
<p>For the normality assumption, we can plot a histogram of the residuals to check that the residuals are approximately normally distributed. Below is the graph.</p>
<div class="cell" data-tags="[]" data-execution_count="36">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot histogram of residuals</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">15</span>,<span class="dv">5</span>))</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>sns.histplot(results.resid)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-normality" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="gpa_analysis_files/figure-html/fig-normality-output-1.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;6: Histogram of resiudals</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>As we can see in <a href="#fig-normality">Figure&nbsp;6</a>, the distribution looks fairly left skewed with a long left tail. For ease of this analysis/exercise, we will say this is “approximately” normal, but this would more than likely fail in the real world.</p>
<p>To verify equal variance, we will view a scatterplot of the fitted vs residual values to make sure that there appears to be equal variance (good randomness, no trends) in the graph.</p>
<div class="cell" data-tags="[]" data-execution_count="41">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot scatterplot of fitted vs residuals</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">15</span>,<span class="dv">5</span>))</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x<span class="op">=</span>results.fittedvalues,y<span class="op">=</span>results.resid)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div id="fig-equal-variance" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="gpa_analysis_files/figure-html/fig-equal-variance-output-1.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;7: Scatterplot of fitted vs residuals</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-equal-variance">Figure&nbsp;7</a>, there appears to be no significant trends in the data (though it does tend to begin to taper as we increase across the x-axis). However, since there is nothing obvious or glaring, we can verify this assumption.</p>
</section>
<section id="do-students-spend-on-average-9-hours-a-week-studying" class="level3" data-number="0.4.5">
<h3 data-number="0.4.5" class="anchored" data-anchor-id="do-students-spend-on-average-9-hours-a-week-studying"><span class="header-section-number">0.4.5</span> Do students spend on average 9 hours a week studying?</h3>
<p>From my past university experience, many professors have told me that for every 1 hour of lecture, should be 3 hours of study/homework time. Assuming this class was a 3 credit hour class, most students should be spending about 9 hours studying outside of class. To test this theory, we will use a t-test for the following hypotheses.</p>
<p><span class="math display">\[H_0: \mu = 9\]</span> <span class="math display">\[H_a: \mu \neq 9\]</span></p>
<div class="cell" data-tags="[]" data-execution_count="44">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Perform t-test to see if students on average spend 9 hours studying</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ttest_1samp</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>ttest_1samp(a<span class="op">=</span>df[<span class="st">'study_hours'</span>], popmean<span class="op">=</span><span class="dv">9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="44">
<pre><code>TtestResult(statistic=10.32185697364204, pvalue=3.767865100544389e-20, df=192)</code></pre>
</div>
</div>
<p>The above result with a super small p-value (less than <span class="math inline">\(\alpha\)</span> = .05) indicates that we can reject the null hypothesis and conclude that students do not study an average of 9 hours for this class. To determine what the range of possible average values are, we will calculate a 95% confidence interval below.</p>
<div class="cell" data-tags="[]" data-execution_count="46">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate 95% confidence interval</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>ttest_1samp(a<span class="op">=</span>df[<span class="st">'study_hours'</span>], popmean<span class="op">=</span><span class="dv">9</span>).confidence_interval()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="46">
<pre><code>ConfidenceInterval(low=15.856880282374465, high=19.096487593273206)</code></pre>
</div>
</div>
<p>We are 95% confident that the true average study time spent is between 15.85 to 19.09 hours. So, on average, students are spending a lot more time studying for this class than the hoped benchmark set by this university (assuming this university has set the same benchmark as my other ones).</p>
</section>
</section>
<section id="bayesian-modeling" class="level2" data-number="0.5">
<h2 data-number="0.5" class="anchored" data-anchor-id="bayesian-modeling"><span class="header-section-number">0.5</span> Bayesian Modeling</h2>
<p>Finally, getting into the bayesian part of the analysis! As with our classical approach, we will layout the framework we will use for this section. We will be using the bayesian model (Bayes theorem) shown below.</p>
<p><span id="eq-bayes-theorem"><span class="math display">\[P(H|\theta) = \frac{P(\theta|H) P(H)}{P(\theta)} \tag{8}\]</span></span></p>
<p><span class="math display">\[H = \text{Our Hypothesis (prior)}\]</span> <span class="math display">\[\theta = \text{Our Data}\]</span></p>


</section>

</main> <!-- /main -->
<div>
	<iframe src="https://embeds.beehiiv.com/8dcdbb8c-72a5-41f4-aecb-68828c82779e" data-test-id="beehiiv-embed" width="100%" height="320" frameborder="0" scrolling="no" style="border-radius: 4px; border: 2px solid #e5e7eb; margin: 0; background-color: transparent;"></iframe>
</div>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>